### ISSUE TITLE
Problems working with the new version 

### ISSUE THREAD

**Issue by Digoba** [deepqmc/deepqmc#203]
Hello, 

I am working with deepqmc in a virtual machine, but I am having troubles while working with the last commit because it seems that there is a problem with the version of CentOS that I am using. 
I am sure that is not a problem of my code because I was using it in another machine, and it works well, but when I move to another virtual machine searching for a better performance, I experienced the error that I mentioned before. 

After all the explanation, can you tell me what versions of deepqmc can work with CentOS 7.9? I also want to know what distribution of linux is the best and what procedure I need to follow because I was trying and trying and nothing seems to work. 

Thanks for all the support.

**Comment by Digoba** [comment]
Hello again,
Now I am having the next issue:
![image](https://github.com/deepqmc/deepqmc/assets/106712012/326eef8f-f3f0-463a-9fae-099c59285aa7)

I created a new environment and started from cero with the installation but nothing seems to work :/.

**Comment by evelynmitchell** [comment]
Can you include the output of ```pip freeze```? It looks to me like a version incompatibility with kfac_jax, but I don't have enough details to be sure.

**Comment by szbernat** [comment]
Hi Digoba,

Sorry for taking so long to reply.

The root cause of the problem mentioned in your second comment is conflicting versions of the deepqmc dependencies. We have updated our `pyproject.toml` with more restrictive versions, see https://github.com/deepqmc/deepqmc/pull/206. The fix is not yet in the released version though, so you'll have to clone this repository and install from source.

Please try a fresh install with the latest version of deepqmc. You should be able to get a functional deepqmc with CPU support by running from the top level deepqmc directory:

```
$ pip install -e .
```

For GPU support, upgrade jax to the GPU version with a matching cuda installation. For cuda 12 this would be

```
$ pip install --upgrade "jax[cuda12_pip]<0.4.24" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

Note the restriction to jax 0.4.23 or lower.

We have found that installing jax 0.4.23 may not enable GPU support on all machines due to issues with the cudnn library. In these cases, running deepqmc results in the following error: `CUDA backend failed to initialize: Unable to load cuDNN. Is it installed?`. A workaround is to downgrade to nvidia-cudnn-cu12==8.9.7.29

```
$ pip install nvidia-cudnn-cu12==8.9.7.29
```

Please let us know if this solves your problem, and don't hesitate to create new issues if you have any other difficulties with running deepqmc.

I would also like to mention that we are working on a new major release of deepqmc which will allow the use of the latest versions of jax, kfac-jax, numpy, etc. and will have a lot of new exciting features.

**Comment by szbernat** [comment]
As for your original comment regarding incompatibility with CentOS:

We unfortunately don't have access to a machine with CentOS, so we can't directly test this setup. In general, I'd be surprised if `deepqmc` was completely incompatible with this specific operating system. In order to be able to further help you, could you describe your problem in a bit more detail?

1. What commands did you run to try and install deepqmc?
2. What was the error when you tried to run deepqmc?
3. Could you please post the output of `pip freeze` of your virtual environment you use to run deepqmc?

**Comment by szbernat** [comment]
Closing this as inactive, feel free to reopen if necessary.
