### ISSUE TITLE
deepqmc.train:Restarting due to a NaN...

### ISSUE THREAD

**Issue by RicardoLopezDoria** [deepqmc/deepqmc#207]
Hi,

I'm still following the tutorial. I'm trying to do the calculations with the predefined LiH molecule. This is my code which I basically copied from the [tutorial](https://deepqmc.github.io/tutorial.html):

`import deepqmc
import os
import haiku as hk
from hydra import compose, initialize_config_dir
from hydra.utils import instantiate
from deepqmc.app import instantiate_ansatz
from deepqmc.wf import NeuralNetworkWaveFunction
from deepqmc import Molecule
from deepqmc import MolecularHamiltonian
from deepqmc.sampling import chain, MetropolisSampler, DecorrSampler
from deepqmc import train

#define molecule and molecular hamiltonian
mol = Molecule.from_name('LiH')
H = MolecularHamiltonian(mol=mol)

#read configuration file
deepqmc_dir = os.path.dirname(deepqmc.file)
config_dir = os.path.join(deepqmc_dir, 'conf/ansatz')

with initialize_config_dir(version_base=None, config_dir=config_dir):
cfg = compose(config_name='default')

_ansatz = instantiate(cfg, recursive=True, convert='all')

ansatz = instantiate_ansatz(H, _ansatz)

sampler = chain(DecorrSampler(length=20),MetropolisSampler(H))

train(H, ansatz, 'kfac', sampler, steps=1000, electron_batch_size=2000, seed=42, workdir='runs/01')`

This is what I get in the terminal:

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

equilibrate sampler: 6%|██████▉ | 62/1000 [02:13<33:33, 2.15s/it, tau=0.262]
training: 0%| | 0/1000 [00:00<?, ?it/s]2024-08-27 16:02:55.285908: E external/xla/xla/service/slow_operation_alarm.cc:65]

[Compiling module pmap__step] Very slow compile? If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.

2024-08-27 16:04:17.656937: E external/xla/xla/service/slow_operation_alarm.cc:133] The operation took 3m22.374570448s

[Compiling module pmap__step] Very slow compile? If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.

training: 33%|███████████████████████████████████████▎ | 333/1000 [44:44<1:29:36, 8.06s/it, E=nan(nan)]
WARNING:deepqmc.train:Restarting due to a NaN...
training: 33%|███████████████████████████████████████▎ | 333/1000 [34:40<1:09:26, 6.25s/it, E=nan(nan)]
WARNING:deepqmc.train:Restarting due to a NaN...
training: 6%|███████ | 59/1000 [13:20<2:14:41, 8.59s/it, E=nan(nan)]

Note the recurrent error: "WARNING:deepqmc.train:Restarting due to a NaN..."

I have no clue what could be the problem. This is the code provided in the tutorial. Could it have to do with me not having CUDA configured (not having access to an NVIDIA card).

**Comment by szbernat** [comment]
Hi,

Running on the CPU should in principle work just as well as running on a GPU. However, this is not tested, as it's much slower than running on a GPU, so it might produce unexpected errors.

Could you send us the output of `pip freeze` in the environment you are using to run deepqmc? The exact version of deepqmc (commit hash) would be especially useful to know, so that we can try and reproduce this error.

**Comment by RicardoLopezDoria** [comment]
Hi, thanks for the response: 

This is the output of pip freeze:
```
absl-py==2.1.0
antlr4-python3-runtime==4.9.3
attrs==24.2.0
black==24.8.0
cfgv==3.4.0
chex==0.1.86
click==8.1.7
cloudpickle==3.0.0
codespell==2.3.0
decorator==5.1.1
-e git+https://github.com/deepqmc/deepqmc@9d9217348e21c401c1aecdb6a87b4e6e7a166154#egg=deepqmc
distlib==0.3.8
distrax==0.1.5
dm-haiku==0.0.12
dm-tree==0.1.8
etils==1.9.2
filelock==3.15.4
flake8==7.1.1
flake8-bugbear==24.4.26
flake8-comprehensions==3.15.0
flake8-quotes==3.4.0
flax==0.8.4
fsspec==2024.6.1
gast==0.6.0
grpcio==1.65.4
h5py==3.11.0
hydra-core==1.3.2
identify==2.6.0
immutabledict==4.2.0
importlib_resources==6.4.0
iniconfig==2.0.0
isort==5.13.2
jax==0.4.23
jax_dataclasses==1.6.1
jaxlib==0.4.23
jmp==0.0.4
kfac-jax==0.0.5
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mccabe==0.7.0
mdurl==0.1.2
ml-dtypes==0.4.0
msgpack==1.0.8
mypy==1.11.1
mypy-extensions==1.0.0
nest-asyncio==1.6.0
nodeenv==1.9.1
numpy==1.26.4
omegaconf==2.3.0
opt-einsum==3.3.0
optax==0.2.2
orbax-checkpoint==0.5.16
packaging==24.1
pathspec==0.12.1
pep8-naming==0.14.1
platformdirs==4.2.2
pluggy==1.5.0
pre-commit==3.8.0
protobuf==4.25.4
pycodestyle==2.12.1
pydocstyle==6.3.0
pyflakes==3.2.0
Pygments==2.18.0
pyscf==2.6.2
pytest==8.3.2
pytest-datadir==1.5.0
pytest-regressions==2.5.0
PyYAML==6.0.2
rich==13.7.1
scipy==1.11.4
setuptools==72.1.0
six==1.16.0
snowballstemmer==2.2.0
tabulate==0.9.0
tensorboard==2.17.0
tensorboard-data-server==0.7.2
tensorflow-probability==0.24.0
tensorstore==0.1.64
toolz==0.12.1
tqdm==4.66.5
typing_extensions==4.12.2
uncertainties==3.2.2
virtualenv==20.26.3
Werkzeug==3.0.3
wheel==0.43.0
zipp==3.20.0

```

And this is the last commit when I cloned the repository:

```
(deepQMC) ricardol@amenadiel:~/deepQMC/deepqmc$ git log
commit 9d9217348e21c401c1aecdb6a87b4e6e7a166154 (HEAD -> master, origin/master, origin/HEAD)
Author: Zeno Schätzle <zenoone@physik.fu-berlin.de>
Date:   Wed Aug 14 10:54:54 2024 +0200

    restrict versions of dependencies
```
Thanks

**Comment by szbernat** [comment]
Hi Ricardo,

I just got around to looking into this issue. Unfortunately, I cannot reproduce your error with the same jax and deepqmc versions as you use, running on a CPU. On my machine, the optimization successfully finished the 1000 training steps.

To give you some background: your error message means that at certain steps of the optimization (333 and then 59), one of the wave function values of the batch was computed to be NaN. This is known to happen occasionally, mostly because the numerics of the whole problem can be pretty difficult to deal with, especially when using single precision as we do. It is rather surprising that these issues pop up during the default training run for LiH, which is known to be a very simple exercise, and almost always proceeds without problems. You could try running one of the other small systems, e.g. `mol = Molecule.from_name('He')`, to see if the errors persist there.

I recently did some tests on Intel GPUs (instead of NVIDIA ones) where I also encountered some unexpected NaN errors. Because of this, I'm suspecting that some processor architectures are more prone to these numerical issues than others. Are you running on an Intel or and AMD CPU? We usually run on Intel CPUs so it could be that AMD ones cause surprises.

In general, if you're planning on using `deepqmc` for "real" calculations (i.e. molecules containing more than 4-6 electrons), having access to NVIDIA GPUs would be crucial. The quantom Monte Carlo algorithm of `deepqmc` is highly parallel in nature, so it's a much better fit for GPUs than CPUs. As a result, running on CPUs is much slower than on GPUs.

**Comment by RicardoLopezDoria** [comment]
Hi, 
Thanks for the response. In my laptop, I have an AMD Radeon graphics card and an AMD Ryzen 7 CPU. I understand your response. For the moment I will try with `mol = Molecule.from_name('He')`  to see if I get better results. 
Thanks.

**Comment by szbernat** [comment]
Closing this as inactive, feel free to reopen if necessary.
