### ISSUE TITLE
logging forces

### ISSUE THREAD

**Issue by dcyang** [deepqmc/deepqmc#215]
Hi,
I noticed you've added forces in v1.2.0. I was trying to get it to work by creating a list of `observable_monitors` which includes `BareForceMonitor`, as mentioned in the [latest tutorial](https://deepqmc.github.io/tutorial.html#logging). But passing it to `train(...)` leads to a logging error under otherwise default settings.
The error I get is 
```
ValueError: Invalid dimension (4) for hf_force_bare/mean (shape: (1, 1, 2, 3)).
```
which I traced to `TensorboardMetricLogger.add_full_dataset_scalars(...)`. This metric logger seems to be the only one available in log.py. Will I have to write my own metric logger which handles 4D arrays as outputs, or is there some other intended way of using `observable_monitors` for forces?
It would be nice if there is a minimal working example for this in the docs...
Thanks in advance.

**Comment by zenoone** [comment]
Hi dcyang,
thanks for creating the issue on DeepQMC! The error you experienced was due to the Tensorboard log not being configured to handle such deeply nested observables.  The problem is fixed in #216.  Please pull to the latest version of DeepQMC to avoid the problem. Note that you may have to install DeepQMC from github if you haven't done so already (see [installation](https://deepqmc.github.io/installation.html#developing)). Do not hesitate to contact us if you have any further questions.
