### ISSUE TITLE
Why are the samples for the next 50 iterations always precomputed?

### ISSUE THREAD

**Issue by n-gao** [deepqmc/deepqmc#23]
Hi, I was wondering why the samples are all taken in one step and then later on used for training. One could also just sample the wavefunction at every iteration resulting in more accurate samples of the current wavefunctions?

**Comment by jhrmnn** [comment]
This strategy isn't supported by some very strong evidence or reasoning, but a result for experiments. We found out that what's most important is that the samples used for training come from an equilibrated sampler. So this would become expensive if you wanted to resample every training step, because you'd need to do the extra equilibration steps every time. For the small systems, we didn't observe any difference in training whether you resample every 50 or 5 steps, the former is just somewhat faster. If you go to larger systems, you need to shorten this period, because the wave function changes more substantially at each step (the KL divergence grows faster at each step), but there it actually doesn't matter because for larger systems, the sampling takes only a negligible time compared to evaluation of the local energy.

**Comment by n-gao** [comment]
Thank you for your insights, very interesting!
