### ISSUE TITLE
energy example discrepancy

### ISSUE THREAD

**Issue by MarcSegovia65** [deepqmc/deepqmc#53]
Hello

I run LiH example in a CPU cluster machine, with sucess , training and evaluation runs well. But if I compare my results , with tutorial shown results there is a huge discrepancy in the energy, my results using default param.toml file is -7.988 Ha and in the tutorial a value of -8.07 Ha is shown.
Is this because tutorial example don't use default param.toml ? larger training ? or can be due to running on CPU instead of GPU, some numerical issue ?
Thanking in advance your help.
Best Regards
Marc

Dr. Marc Segovia
CCBG-DETEMA
Universidad de la Republica
Montevideo-Uruguay

**Comment by jhrmnn** [comment]
Hi. By the "LiH example", do you mean what's in the README or in the documentation tutorial [here](https://deepqmc.github.io/tutorial.html)?

**Comment by MarcSegovia65** [comment]
Hello
In the documentation tutorial, where GET THE ENERGY subtitle .

**Comment by MarcSegovia65** [comment]
Hello Jan


In the documentation tutorial, where GET THE ENERGY subtitle .

Best Regards
Marc

**Comment by jhrmnn** [comment]
Sorry, you have closed the issue, so I assumed that you found out what the problem was.

The tutorial example doesn't use `param.toml`, so I'm not sure what you mean by that. But in any case I've just reran the tutorial and got the same results. Using a GPU or not should certainly not affect the results, only performance.

The energy you're getting is suspiciously close to the HF baseline, are you certain that you actually use the `cas` parameter and that you're evaluating a trained model?

For reference, this is a script that I just ran and got energy of -8.0482(30) after 40 steps of training.

```python
from deepqmc import train, evaluate, Molecule
from deepqmc.wf import PauliNet

mol = Molecule(
    coords=[[0.0, 0.0, 0.0], [3.0, 0.0, 0.0]],
    charges=[3, 1],
    charge=0,
    spin=0,
)
net = PauliNet.from_hf(mol, cas=(4, 2)).cuda()
train(net, n_steps=40)
evaluate(net)
```

**Comment by MarcSegovia65** [comment]
Hi Jan

sorry , I have little experience with github issues.
You found  my mistake,  didn't use cas, mistake understood.

Thank you by your help,

Best regards

Marc
